
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
- repo: self

variables:
  azureServiceConnection: 'azure-aks-connection'
  azureContainerRegistry: '1dtteam1registry.azurecr.io'
  imageRepository: 'itc-app'
  azureResourceGroup: '1dt-final-team1'
  kubernetesCluster: '1dt-team1-aks'
  dockerRegistryServiceConnection: 'acr-connection'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'npm install'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/k8s'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool: Default
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'manifests'
              path: '$(Pipeline.Workspace)/manifests'

          - task: replacetokens@3
            displayName: 'Replace tokens in Kubernetes manifests'
            inputs:
              targetFiles: '$(Pipeline.Workspace)/manifests/deployment.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
              useLegacyPattern: false
              variables: 'IMAGE = $(azureContainerRegistry)/$(imageRepository):$(tag)'

          - task: KubeCtlInstaller@0
            displayName: 'Install Kubectl'
            inputs:
              kubectlVersion: 'latest'

          - task: AzureCLI@2
            displayName: 'Install kubelogin and Deploy to AKS'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # kubelogin 최신 버전 다운로드 및 설치
                echo "Installing kubelogin..."
                KUBELOGIN_VERSION=$(curl -s https://api.github.com/repos/Azure/kubelogin/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
                curl -LO "https://github.com/Azure/kubelogin/releases/download/${KUBELOGIN_VERSION}/kubelogin-linux-amd64.zip"
                unzip kubelogin-linux-amd64.zip
                sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
                kubelogin --version
                
                # AKS 자격 증명 가져오기
                echo "Getting AKS credentials..."
                az aks get-credentials --resource-group $(azureResourceGroup) --name $(kubernetesCluster) --overwrite-existing
                
                # kubelogin을 사용하여 kubeconfig 변환
                echo "Converting kubeconfig for Azure CLI authentication..."
                kubelogin convert-kubeconfig -l azurecli
                
                # 클러스터 연결 테스트
                echo "Testing cluster connection..."
                kubectl get nodes
                
                # Kubernetes 매니페스트 배포
                echo "Deploying manifests..."
                kubectl apply -f $(Pipeline.Workspace)/manifests/
                
                # 배포 상태 확인
                echo "Checking deployment status..."
                kubectl get pods -o wide
                kubectl get services