trigger:
- main

variables:
  dockerRegistryServiceConnection: 'acr-connection'
  azureServiceConnection: 'azure-aks-connection'
  azureResourceGroup: '1dt-final-team1'
  kubernetesCluster: '1dt-team1-aks'
  azureContainerRegistry: '1dtteam1registry.azurecr.io'
  imageRepository: 'itc-app'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Stage 1: Build and Push'
  jobs:
  - job: BuildJob
    displayName: 'Build and Push Job'
    steps:
    - task: Docker@2
      displayName: 'Build and Push image to ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: '$(tag)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Kubernetes manifests'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/k8s'
        artifact: 'manifests'

- stage: Deploy
  displayName: 'Stage 2: Deploy to AKS'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to AKS Job'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Kubernetes manifests'
            inputs:
              artifact: 'manifests'
              path: '$(Pipeline.Workspace)/manifests'

          - task: replacetokens@3
            displayName: 'Replace image token'
            inputs:
              targetFiles: '$(Pipeline.Workspace)/manifests/deployment.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
              useLegacyPattern: false
              variables: 'IMAGE = $(azureContainerRegistry)/$(imageRepository):$(tag)'

          - task: AzureCLI@2
            displayName: 'Deploy to AKS using Admin Credentials'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -e
                echo "Getting AKS admin credentials..."
                az aks get-credentials --resource-group $(azureResourceGroup) --name $(kubernetesCluster) --admin --overwrite-existing
                
                echo "Ensuring namespace 'itc' exists..."
                kubectl create namespace itc || echo "Namespace 'itc' already exists."

                echo "Applying Kubernetes manifests to 'itc' namespace..."
                kubectl apply -f $(Pipeline.Workspace)/manifests --namespace itc